name: 'PPML-spark-Local-Example-Tests-on-Gramine'
description: 'PPML-spark-Local-Example-Tests-on-Gramine'
inputs:
  image-tag:
    description: 'image tag'
    required: true
    default: 'latest'
runs:
  using: "composite"
  steps:
    - name: Set Variable
      shell: bash
      env:
        DEFAULT_SGX_MEM_SIZE: 32G
        DEFAULT_IMAGE: 10.239.45.10/arda/intelanalytics/bigdl-ppml-trusted-big-data-ml-python-gramine:${{ inputs.image-tag }}
      run: |
        echo "IMAGE=${{ env.DEFAULT_IMAGE }}" >> $GITHUB_ENV
