name: Log latest release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/liu-shaojun/test-repo/actions/workflows/retry.yml/runs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      - run: |
          echo '${{ steps.get_latest_release.outputs.data }}' | jq '.workflow_runs[].event==workflow_dispatch'
      
