name: Log latest release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/intel-analytics/BigDL/actions/workflows/nightly_test.yml/runs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      - run: |
          run_id=`echo '${{ steps.get_latest_release.outputs.data }}' | jq --arg today $(date +%Y-%m-%d) '.workflow_runs[] | if .event == "schedule" and .status == "completed" and .created_at[:10] == $today then .id else null end | values'`
          echo $run_id
