name: Manually Build

# Cancel previous runs in the PR when you push new commits
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true


env:
  #Branch: ${{ github.event.inputs.branch }}
  Branch: master

on:
  pull_request:

#   schedule:
#     - cron: '*/6 * * * *'  # GMT time, 15:30 GMT == 23:30 China


permissions:
  contents: read
  packages: write


jobs:

  test_env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: bigdl-ppml-gramine-base
      run: |
        echo ${{ env.Branch }}
        echo ${Branch}
        echo $Branch


